# Generated by Django 3.1.1 on 2020-10-10 11:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0004_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ManyToManyField(related_query_name='tagUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
