# Generated by Django 3.1.1 on 2020-10-10 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_auto_20201010_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, choices=[('nam', 'nam'), ('nữ', 'nữ')], max_length=25, null=True),
        ),
    ]
